### PR TITLE
Improving README.MD

### PR DESCRIPTION
**Pull request by lucis**
I've created a simple text describing the repo and also listed the contents, all in English

### CODE REVIEW

**Comment by xaca** [comment]
Great, thanks

**Comment by lucis** [comment]
You are welcome! I guess it was my first contribution to open-source :D

**Comment by xaca** [comment]
@lucianolucianoluciano good start, we need more help if you have some extra time to share with us

**Comment by xaca** [comment]
@lucianolucianoluciano I have a question, "cadena" in spanish is the translation to String, is correct to use chain to talk about strings. My question is because I design a badge and I named "breaker of chains" is Correct?

**Comment by lucis** [comment]
Oh... I thought you were talking about chains & collections in general, not specifically about string...  

Chain, in english, may refer to the steel part and also to talk about a group of something. In portuguese, my mother language, it has two separate words. Gonna change that ;)

**Comment by lucis** [comment]
#8

**Pull request merged**
