### PR TITLE
Decimal to Binary Conversion using Recursions

### PR DESCRIPTION
**Pull request by its-snorlax**

### CODE REVIEW

**Comment by xaca** [comment]
@minijainsahab Thank you! There is some reason to have to classes? The question is because we could use in your soulition a static method. Do you know why?

**Comment by its-snorlax** [comment]
@xaca is it okay, if I do second pull request having the static method?

**Comment by xaca** [comment]
@minijainsahab both approaches are ok. Rewrite the code using a static method could be a problem to solve. Thank you

**Comment by its-snorlax** [comment]
Thanks!

**Pull request merged**
